import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import AntiDebugger from "@/components/AntiDebugger";
import MaxWidthWrapper from "@/components/MaxWidthWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<AntiDebugger />
			</head>
			<body className={`text-foreground bg-background ${inter.className}`}>
				<Providers>
					<MaxWidthWrapper className="flex flex-col min-h-screen justify-center items-center">
						{children}
					</MaxWidthWrapper>
				</Providers>
			</body>
		</html>
	);
}
